# Generated by Django 3.2.5 on 2021-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='img_url',
            field=models.URLField(default='http://placekitten.com/g/200/300'),
        ),
    ]
